# Generated by Django 5.1.6 on 2025-02-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('student_name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('3A', '3º Administração'), ('3DS', '3º Desenvolvimento de Sistemas'), ('3E', '3º Enfermagem'), ('3I', '3º Informática'), ('3L', '3º Logística')], max_length=3)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
