# Generated by Django 5.1.6 on 2025-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0002_alter_selection_email_alter_selection_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='tier',
            field=models.CharField(choices=[('3A', '3º Administração'), ('3DS', '3º Desenvolvimento de Sistemas'), ('3E', '3º Enfermagem'), ('3I', '3º Informática')], max_length=3),
        ),
    ]
