# Generated by Django 5.1.6 on 2025-02-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0003_alter_selection_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
